blank_issues_enabled: true
contact_links:
  - name: Installation Help
    url: https://discord.gg/freehost
    about: Please visit our Discord for help with your installation.
  - name: General Question
    url: https://discord.gg/freehost
    about: Please visit our Discord for general questions about Halix Cloud.
  - name: Documentation
    url: https://halix.cloud
    about: Our documentation may have an answer for your issue/question.